org.gradle.jvmargs=-Xmx3G

group=levosilimo.everlastingskins

mod_id=everlastingskins
mod_version=2.0.0
mod_name=EverlastingSkins
mod_vendor=Levosilimo
mod_license=MIT
mod_group_id=levosilimo.everlastingskins
mod_authors=Levosilimo
mod_description=Server-side persistent custom skins on pure Forge legacy servers (1.12.2 probe build).

minecraft_version=1.12.2
minecraft_version_range=[1.12.2,1.13)
forge_version=14.23.5.2860
forge_version_range=[14.23.5.2860,15)
loader_version_range=[14.23.5.2860,15)
