org.gradle.jvmargs=-Xmx3G

group=levosilimo.everlastingskins

mod_id=everlastingskins
mod_version=2.1.0-beta.1
mod_name=EverlastingSkins
mod_vendor=Levosilimo
mod_license=MIT
mod_group_id=levosilimo.everlastingskins
mod_authors=Levosilimo
mod_description=Server-side persistent custom skins on pure Forge legacy servers (1.8.9).

minecraft_version=1.8.9
forge_version=11.15.1.2318
mcp_mappings=stable_20
curse_versions=1.8.9
