online-mode=false
enforce-secure-profile=false
server-port=25565
motd=EverlastingSkins Test Server
gamemode=survival
difficulty=easy
pvp=false
spawn-animals=false
spawn-monsters=false
enable-command-block=true
max-players=5
view-distance=4
