/*
 * SPDX-License-Identifier: MIT
 * Copyright (c) 2026 Levosilimo
 * https://github.com/Levosilimo/Everlasting-Skins
 */

package levosilimo.everlastingskins.forge147;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLServerStartingEvent;
import cpw.mods.fml.common.event.FMLServerStoppingEvent;
import cpw.mods.fml.common.network.IConnectionHandler;
import cpw.mods.fml.common.network.NetworkRegistry;
import cpw.mods.fml.common.network.Player;
import levosilimo.everlastingskins.broadcast.SkinBroadcaster;
import levosilimo.everlastingskins.permission.forge.ForgePermissionService;
import levosilimo.everlastingskins.skinchanger.SkinRestorer;
import net.minecraft.server.MinecraftServer;
import net.minecraft.src.EntityPlayer;
import net.minecraft.src.EntityPlayerMP;
import net.minecraft.src.INetworkManager;
import net.minecraft.src.NetHandler;
import net.minecraft.src.NetLoginHandler;
import net.minecraft.src.Packet1Login;

/**
 * 1.4.7 entry point. FML 4.7.35 surface (pre-1.6 lifecycle markers): there is
 * no {@code @Mod.EventHandler} on this line — the lifecycle annotations are
 * {@code @Mod.Init} / {@code @Mod.ServerStarting} / {@code @Mod.ServerStopping}
 * (the {@code EventHandler} umbrella arrived in FML 5.x). No GameProfile, no
 * {@code PlayerEvent} gameevent package and no {@code @SubscribeEvent} — the
 * pre-1.7 player join/leave surface is {@link IConnectionHandler}, registered
 * via {@link NetworkRegistry#registerConnectionHandler}.
 *
 * <p>Skin storage stays UUID-keyed in :common via a lane-local username
 * bridge ({@link SkinRestorer#uuidOf(String)}): 1.4.7 has no player-resolvable
 * account UUID, so the binding boundary derives a deterministic offline-style
 * UUID from {@code getCommandSenderName()} and :common never sees a player
 * object (memory #1123 contract, unchanged).
 *
 * <p>Network surface: FML 4.7 {@code Packet250CustomPayload} custom-payload
 * channel, registered in {@link #init} via
 * {@code NetworkRegistry.instance().registerChannel(...)} — the channel name
 * {@code everlastingskins} is exactly 16 chars, at the 1.4.7 hard cap.
 */
@Mod(
    modid = EverlastingSkins.MOD_ID,
    name = EverlastingSkins.MOD_NAME,
    version = EverlastingSkins.VERSION,
    acceptedMinecraftVersions = "[1.4.7]"
)
public class EverlastingSkins {
    public static final String MOD_ID = "everlastingskins";
    public static final String MOD_NAME = "EverlastingSkins";
    // Compile-time constant generated by the build (no FG `replace` on this
    // harness) — keeps @Mod's version in sync with gradle.properties.
    public static final String VERSION = ModVersion.VERSION;

    @Mod.Init
    public void init(FMLInitializationEvent event) {
        // :common removed init() — per-version bootstrap registers candidates
        // itself; highest priority wins (Forge ops 10 > vanilla fallback 0).
        ForgePermissionService.register();
        // 1.4.7 skin-broadcast channel (FML 4.7 custom-payload surface).
        SkinBroadcaster.init();
        // Pre-1.7 player join/leave hook (no PlayerEvent on this line).
        NetworkRegistry.instance().registerConnectionHandler(new ConnectionHandler());
    }

    @Mod.ServerStarting
    public void serverStarting(FMLServerStartingEvent event) {
        SkinRestorer.onServerStarting(event);
    }

    @Mod.ServerStopping
    public void serverStopping(FMLServerStoppingEvent event) {
        SkinRestorer.onServerStopping(event);
    }

    /**
     * 1.4.7 connection lifecycle: {@code playerLoggedIn} is player-keyed,
     * {@code connectionClosed} is manager-keyed (the player must be resolved
     * from the manager by {@link SkinRestorer#onConnectionClosed}).
     */
    private static final class ConnectionHandler implements IConnectionHandler {

        @Override
        public void playerLoggedIn(Player player, NetHandler netHandler, INetworkManager manager) {
            if (player instanceof EntityPlayerMP) {
                SkinRestorer.onPlayerLoggedIn((EntityPlayer) player);
            }
        }

        @Override
        public String connectionReceived(NetLoginHandler netHandler, INetworkManager manager) {
            return null;
        }

        @Override
        public void connectionOpened(NetHandler netClientHandler, String server, int port, INetworkManager manager) {
        }

        @Override
        public void connectionOpened(NetHandler netClientHandler, MinecraftServer server, INetworkManager manager) {
        }

        @Override
        public void connectionClosed(INetworkManager manager) {
            SkinRestorer.onConnectionClosed(manager);
        }

        @Override
        public void clientLoggedIn(NetHandler netClientHandler, INetworkManager manager, Packet1Login login) {
        }
    }
}
