/*
 * SPDX-License-Identifier: MIT
 * Copyright (c) 2026 Levosilimo
 * https://github.com/Levosilimo/Everlasting-Skins
 */

package levosilimo.everlastingskins.forge164;

import cpw.mods.fml.common.FMLCommonHandler;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLServerStartingEvent;
import cpw.mods.fml.common.event.FMLServerStoppingEvent;
import cpw.mods.fml.common.network.IConnectionHandler;
import cpw.mods.fml.common.network.NetworkMod;
import cpw.mods.fml.common.network.NetworkRegistry;
import levosilimo.everlastingskins.e2e.E2E;
import cpw.mods.fml.common.network.Player;
import levosilimo.everlastingskins.broadcast.ClientSkinHandler;
import levosilimo.everlastingskins.broadcast.ServerPacketHandler;
import levosilimo.everlastingskins.broadcast.SkinBroadcaster;
import levosilimo.everlastingskins.permission.forge.ForgePermissionService;
import levosilimo.everlastingskins.skinchanger.SkinRestorer;
import net.minecraft.server.MinecraftServer;
import net.minecraft.src.EntityPlayer;
import net.minecraft.src.EntityPlayerMP;
import net.minecraft.src.INetworkManager;
import net.minecraft.src.NetHandler;
import net.minecraft.src.NetLoginHandler;
import net.minecraft.src.Packet1Login;

/**
 * 1.6.4 entry point. FML 7.x / LaunchWrapper surface (pre-ModLauncher):
 * classes live under {@code cpw.mods.fml.*}, there is no GameProfile, no
 * {@code PlayerEvent} gameevent package and no {@code @SubscribeEvent} —
 * the pre-1.7 player join/leave surface is {@link IConnectionHandler},
 * registered via {@link NetworkRegistry#registerConnectionHandler}.
 *
 * <p>Skin storage stays UUID-keyed in :common via a lane-local username
 * bridge ({@link SkinRestorer#uuidOf(String)}): 1.6.4 has no player-resolvable
 * account UUID, so the binding boundary derives a deterministic offline-style
 * UUID from {@code getCommandSenderName()} and :common never sees a player
 * object (memory #1123 contract, unchanged).
 *
 * <p>Network surface: JOINT jar (lib-5 Option B, PR #422) — the channel
 * {@code everlastingskins} (exactly 16 chars, at the 1.6.4 hard cap) is
 * registered by the {@link NetworkMod} joint pattern below, NOT by a manual
 * {@code registerChannel}: FML's {@code NetworkModHandler.configureNetworkMod}
 * registers the client spec ({@link ClientSkinHandler}) only when
 * {@code FMLCommonHandler.instance().getSide().isClient()} and the server spec
 * ({@link ServerPacketHandler}) on both sides (dispatch is side-separated via
 * {@code NetworkRegistry.handlePacket}'s EntityPlayerMP check), so one jar
 * declares both and each process runs only its own receiver.
 *
 * <p>Side guard: FML loads the jar on both processes, so {@link #init} keeps
 * the server bootstrap behind {@code getSide().isServer()} — on a client the
 * only client-side surface is the @NetworkMod-registered client handler.
 */
@Mod(
    modid = EverlastingSkins.MOD_ID,
    name = EverlastingSkins.MOD_NAME,
    version = EverlastingSkins.VERSION,
    acceptedMinecraftVersions = "[1.6.4]"
)
@NetworkMod(
    clientPacketHandlerSpec = @NetworkMod.SidedPacketHandler(
        channels = {SkinBroadcaster.CHANNEL},
        packetHandler = ClientSkinHandler.class),
    serverPacketHandlerSpec = @NetworkMod.SidedPacketHandler(
        channels = {SkinBroadcaster.CHANNEL},
        packetHandler = ServerPacketHandler.class)
)
public class EverlastingSkins {
    public static final String MOD_ID = "everlastingskins";
    public static final String MOD_NAME = "EverlastingSkins";
    // Compile-time constant generated by the build (no FG `replace` on this
    // harness) — keeps @Mod's version in sync with gradle.properties.
    public static final String VERSION = ModVersion.VERSION;

    @Mod.EventHandler
    public void init(FMLInitializationEvent event) {
        if (!FMLCommonHandler.instance().getSide().isServer()) {
            // Client process: the client handler is registered by @NetworkMod;
            // no server bootstrap here (the physical side is authoritative —
            // an integrated server's SERVER lifecycle still fires
            // serverStarting/serverStopping below).
            return;
        }
        // :common removed init() — per-version bootstrap registers candidates
        // itself; highest priority wins (Forge ops 10 > vanilla fallback 0).
        ForgePermissionService.register();
        // In-jar E2E support (shipped-gated by -Deverlastingskins.e2e=true;
        // no-op in production).
        E2E.install();
        // Pre-1.7 player join/leave hook (no PlayerEvent on this line). The
        // broadcast channel itself is owned by @NetworkMod.
        NetworkRegistry.instance().registerConnectionHandler(new ConnectionHandler());
    }

    @Mod.EventHandler
    public void serverStarting(FMLServerStartingEvent event) {
        SkinRestorer.onServerStarting(event);
    }

    @Mod.EventHandler
    public void serverStopping(FMLServerStoppingEvent event) {
        SkinRestorer.onServerStopping(event);
    }

    /**
     * 1.6.4 connection lifecycle: {@code playerLoggedIn} is player-keyed,
     * {@code connectionClosed} is manager-keyed (the player must be resolved
     * from the manager by {@link SkinRestorer#onConnectionClosed}).
     */
    private static final class ConnectionHandler implements IConnectionHandler {

        @Override
        public void playerLoggedIn(Player player, NetHandler netHandler, INetworkManager manager) {
            if (player instanceof EntityPlayerMP) {
                SkinRestorer.onPlayerLoggedIn((EntityPlayer) player);
            }
        }

        @Override
        public String connectionReceived(NetLoginHandler netHandler, INetworkManager manager) {
            return null;
        }

        @Override
        public void connectionOpened(NetHandler netClientHandler, String server, int port, INetworkManager manager) {
        }

        @Override
        public void connectionOpened(NetHandler netClientHandler, MinecraftServer server, INetworkManager manager) {
        }

        @Override
        public void connectionClosed(INetworkManager manager) {
            SkinRestorer.onConnectionClosed(manager);
        }

        @Override
        public void clientLoggedIn(NetHandler netClientHandler, INetworkManager manager, Packet1Login login) {
        }
    }
}
