name: Test Env
on:
  push:
    branches: ["1.21"]
env:
  TEST_VAR: hello
jobs:
  test:
    name: Env Test
    runs-on: ubuntu-latest
    if: github.ref_name == '1.21'
    steps:
      - run: echo "env works: $TEST_VAR"
