name: Test Pull
on:
  push:
    branches: ["1.21"]
  pull_request:
    branches: ["1.21"]
jobs:
  test:
    runs-on: ubuntu-latest
    if: github.ref_name == '1.21' || github.base_ref == '1.21'
    steps:
      - run: echo "Trigger ${{ github.event_name }} ref=${{ github.ref_name }}"
