name: Test Env 4
on:
  push:
    branches: ["1.21"]
jobs:
  test:
    name: Env In Step
    runs-on: ubuntu-latest
    steps:
      - name: Step with env
        env:
          TEST_VAR: hello
        run: echo "env works: $TEST_VAR"
